services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ctp-hackathon
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./:/app

